openapi: 3.0.3
info:
  version: 1.0.0
  title: RBKmoney Fraudbusters API
  description:
    $ref: './docs/api.md'
  termsOfService: 'https://rbk.money/'
  contact:
    name: RBKmoney Support Team
    email: support@rbk.money
    url: 'https://developer.rbk.money'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - bearer: [ ]
tags:
  - name: inspector
    x-displayName: Инспектор
  - name: load-data
    x-displayName: Загрузка исторических данных
  - name: error-codes
    x-displayName: Коды ошибок
    description:
      $ref: './docs/error-codes.md'
paths:
  /fraudbusters/inspect-payment:
    $ref: ./paths/inspectPayment.yaml
  /fraudbusters/chargebacks:
    $ref: ./paths/chargebacks.yaml
  /fraudbusters/fraud-payments:
    $ref: ./paths/fraudPayments.yaml
  /fraudbusters/payments:
    $ref: ./paths/payments.yaml
  /fraudbusters/refunds:
    $ref: ./paths/refunds.yaml
  /fraudbusters/withdrawals:
    $ref: ./paths/withdrawals.yaml
servers:
  - url: 'https://api.rbk.money/org/v1'
